<?php
$fullpage = $_REQUEST['page'];
$param = preg_split("/\//", $fullpage, -1, PREG_SPLIT_NO_EMPTY);
?>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="position: fixed; top: 0; right: 0; left: 0; z-index: 1030;">
  <a class="navbar-brand" href="#"><?php echo $config["sitename"] ?></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav" style="margin-right: auto !important;">
      <li class="nav-item <?php if ($param[0] == "home") {
                            echo "active";
                          } ?>">
        <a class="nav-link" href="/home">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item <?php if ($param[0] == "profile") {
                            echo "active";
                          } ?>">
        <a class="nav-link" href="/profile">Profile</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Otros
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<?php echo $config["fullsiteurl"]; ?>logout">Logout</a>
      </li>
    </ul>
    <div class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" id="search_textbox" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" onclick="do_search()">Search</button>
      <script>
        const do_search = () => {
          let concept = $("#search_textbox").val();
          let nexturl = "<?php echo $config['fullsiteurl'] . "search/" ?>" + concept;
          window.location.href = nexturl;
        }
      </script>
    </div>
  </div>
</nav>
<style>
  .pick_theme_preview {
    flex: 1 1 10px;
    margin: 10px;
  }

  .overlay_menu {
    display: none;
    position: fixed;
    top: 10%;
    left: 5%;
    background-color: var(--bs-body-bg);
    border: 4px solid gold;
    border-radius: 10px;
    padding: 10px;
    width: 90%;
    z-index: 10;
    flex-wrap: wrap;
    overflow: auto;
    max-height: 70%
  }

  .selected-item {
    border: 5px solid gold;
  }

  .menu-selection {
    flex-wrap: wrap;
  }

  @media(min-width: 1000px) {

    /* ESCRITORIO */
    .overlay_menu {
      display: none;
      position: fixed;
      top: 10%;
      left: 20%;
      background-color: var(--bs-body-bg);
      border: 4px solid gold;
      border-radius: 10px;
      width: 60%;
      z-index: 10;
      flex-wrap: wrap;
      overflow: auto;
      max-height: 70%
    }
  }
</style>
<script>
  function setTheme(theme) {

  }
</script>
<div class="overlay_menu">
  <div class="menu_selection">
    <img class="pick_theme_preview" onclick="setTheme('cyborg')" src="https://dummyimage.com/100x150/000/fff" alt="Darkly">
    <img class="pick_theme_preview" onclick="setTheme('darkly')" src="https://dummyimage.com/100x150/000/fff" alt="Darkly">
    <img class="pick_theme_preview" onclick="setTheme('litera')" src="https://dummyimage.com/100x150/000/fff" alt="Darkly">
    <img class="pick_theme_preview" onclick="setTheme('minty')" src="https://dummyimage.com/100x150/000/fff" alt="Darkly">
    <img class="pick_theme_preview" onclick="setTheme('quartz')" src="https://dummyimage.com/100x150/000/fff" alt="Darkly">
  </div>
  <button type="button" class="btn btn-success">Cerrar</button>
</div>