<?php
$fullpage = $_REQUEST['page'];
$param = preg_split("/\//", $fullpage, -1, PREG_SPLIT_NO_EMPTY);
?>
<nav class="navbar navbar-expand-lg navbar-light <?php if (!$useQuartzTheme) {
                                                    echo "bg-light";
                                                  } ?>" style="position: fixed; top: 0; right: 0; left: 0; z-index: 1030;">
  <a class="navbar-brand" href="<?=$config["fullsiteurl"]?>"><?php echo $config["sitename"] ?></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav" style="margin-right: auto !important;">
      <li class="nav-item <?php if ($param[0] == "home") {
                            echo "active";
                          } ?>">
        <a class="nav-link" href="/home">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item <?php if ($param[0] == "profile") {
                            echo "active";
                          } ?>">
        <a class="nav-link" href="/profile">Profile</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Otros
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <button class="dropdown-item" onclick="toggleThemePicker()" href="#">Cambiar tema</button>
          <a class="dropdown-item" href="<?=$config['fullsiteurl']."editprofile"?>">Mi cuenta</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="/landing">Landing</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<?php echo $config["fullsiteurl"]; ?>logout">Logout</a>
      </li>
    </ul>
    <div class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" id="search_textbox" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" style="color:var(--primary); border-color:var(--primary)" onclick="do_search()">Search</button>
      <script>
        const do_search = () => {
          let concept = $("#search_textbox").val();
          let nexturl = "<?php echo $config['fullsiteurl'] . "search/" ?>" + concept;
          window.location.href = nexturl;
        }
      </script>
    </div>
  </div>
</nav>
<style>
  .themePickerWrapper {
    padding: 10px;
    filter: none;
  }

  .pick_theme_preview {
    flex: 1 1 10px;
    margin-right: 10px;
    margin-bottom: 10px;
    width: 100px;
    height: 150px;
    object-fit: fill;
    cursor: pointer;
    border: 1px solid gold;
    border-radius: 5px;
  }

  .overlay_menu_hide {
    display: none;
    position: fixed;
    top: 15%;
    left: 5%;
    background-color: var(--bs-body-bg);
    border: 4px solid gold;
    border-radius: 10px;
    width: 90%;
    z-index: 10000;
    flex-wrap: wrap;
    overflow: auto;
    max-height: 70%
  }

  .selected-item {
    border: 5px solid gold;
  }

  .menu-selection {
    flex-wrap: wrap;
  }

  @media(min-width: 1000px) {

    /* ESCRITORIO */
    .overlay_menu {
      display: block;
      position: fixed;
      top: 25%;
      left: 20%;
      background-color: var(--bs-body-bg);
      border: 4px solid gold;
      border-radius: 10px;
      width: 60%;
      z-index: 10;
      flex-wrap: wrap;
      overflow: auto;
      max-height: 70%
    }

    .overlay_menu_hide {
      display: none;
      position: fixed;
      top: 25%;
      left: 20%;
      background-color: var(--bs-body-bg);
      border: 4px solid gold;
      border-radius: 10px;
      width: 60%;
      z-index: 10;
      flex-wrap: wrap;
      overflow: auto;
      max-height: 70%
    }
  }
  html{
    min-height: 100%;
  }
</style>
<script>
  function myToken() {
    cookie = document.cookie.split('; ').reduce((prev, current) => {
      const [name, ...value] = current.split('=');
      prev[name] = value.join('=');
      return prev;
    }, {});
    return cookie.token
  }
  const siteURL = "<?php echo $config["fullsiteurl"] ?>"
  async function setTheme(theme) {
    console.log("Theme: " + theme)
    token = myToken();

    $.post(siteURL + "api/update/theme_variable", {
      "token": token,
      "newTheme": theme
    }, ).done(function(data) {
      let response = data;
      console.log("------------DONE------------")
      console.log(response);
      console.log("------------DONE------------")
      location.reload()
    }).fail(function(xhr, status, error) {
      console.log("------------FAIL------------")
      console.log(xhr);
      console.log("----------------------------")
      console.log(status);
      console.log("----------------------------")
      console.log(error);
      console.log("------------FAIL------------")
    });
  }
  var themePickerIsVisible = true;

  function toggleThemePicker() {
    if (themePickerIsVisible) {
      //hide
      $("#themePicker").fadeIn(100)
    } else {
      //show
      $("#themePicker").fadeOut(100)
    }
    themePickerIsVisible = !themePickerIsVisible;
  }
</script>
<div class="overlay_menu_hide" id="themePicker">
  <div class="themePickerWrapper">

    <div class="menu_selection">
      <img class="pick_theme_preview" onclick="setTheme('default');" src="<?php echo $config["fullsiteurl"] . "themes/" . $config['theme'] . "/" ?>assets/img/default_theme.png" alt="default">
      <img class="pick_theme_preview" onclick="setTheme('cyborg');" src="<?php echo $config["fullsiteurl"] . "themes/" . $config['theme'] . "/" ?>assets/img/cyborg.png" alt="cyborg">
      <img class="pick_theme_preview" onclick="setTheme('darkly');" src="<?php echo $config["fullsiteurl"] . "themes/" . $config['theme'] . "/" ?>assets/img/darkly.png" alt="darkly">
      <img class="pick_theme_preview" onclick="setTheme('litera');" src="<?php echo $config["fullsiteurl"] . "themes/" . $config['theme'] . "/" ?>assets/img/litera.png" alt="litera">
      <img class="pick_theme_preview" onclick="setTheme('minty');" src="<?php echo $config["fullsiteurl"] . "themes/" . $config['theme'] . "/" ?>assets/img/minty.png" alt="minty">
      <img class="pick_theme_preview" onclick="setTheme('quartz');" src="<?php echo $config["fullsiteurl"] . "themes/" . $config['theme'] . "/" ?>assets/img/quartz.png" alt="quartz">
      <img class="pick_theme_preview" onclick="setTheme('morph');" src="<?php echo $config["fullsiteurl"] . "themes/" . $config['theme'] . "/" ?>assets/img/morph.png" alt="morph">
      <img class="pick_theme_preview" onclick="setTheme('vapor');" src="<?php echo $config["fullsiteurl"] . "themes/" . $config['theme'] . "/" ?>assets/img/vapor.png" alt="vapor">
      <img class="pick_theme_preview" onclick="setTheme('lux');" src="<?php echo $config["fullsiteurl"] . "themes/" . $config['theme'] . "/" ?>assets/img/lux.png" alt="lux">
      <img class="pick_theme_preview" onclick="setTheme('journal');" src="<?php echo $config["fullsiteurl"] . "themes/" . $config['theme'] . "/" ?>assets/img/journal.png" alt="journal">
    </div>
    <button type="button" onclick="toggleThemePicker()" class="btn btn-success">Cerrar</button>
  </div>
</div>