<?php
$fullpage = $_REQUEST['page'];                                   
$param = preg_split("/\//", $fullpage, -1, PREG_SPLIT_NO_EMPTY); 
?>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="position: fixed; top: 0; right: 0; left: 0; z-index: 1030;">
  <a class="navbar-brand" href="#"><?php echo $config["sitename"] ?></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <?php if ($param[0] == "home") {echo "active"; }?>">
        <a class="nav-link" href="/home">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item <?php if ($param[0] == "profile") {echo "active"; }?>">
        <a class="nav-link" href="/profile">Profile</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<?php echo $config["fullsiteurl"]; ?>logout">Logout</a>
      </li>
    </ul>
    <div class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" id="search_textbox" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" onclick="do_search()">Search</button>
      <script>
        const do_search = () => {
          let concept = $("#search_textbox").val();
          let nexturl = "<?php echo $config['fullsiteurl'] . "search/" ?>" + concept;
          window.location.href = nexturl;
        }
      </script>
    </div>
  </div>
</nav>